### ISSUE TITLE
Incompatible with Python3.7

### ISSUE THREAD

**Issue by ashishnitinpatil** [driveate/ws-api-client-python#1]
Gives the following error when importing -

```python
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ws_api_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/ws_api_client/__init__.py", line 19, in <module>
    from ws_api_client.api.bolt_patterns_api import BoltPatternsApi
  File "/usr/local/lib/python3.7/dist-packages/ws_api_client/api/__init__.py", line 6, in <module>
    from ws_api_client.api.bolt_patterns_api import BoltPatternsApi
  File "/usr/local/lib/python3.7/dist-packages/ws_api_client/api/bolt_patterns_api.py", line 157
    async=params.get('async'),
        ^
SyntaxError: invalid syntax

```

For now I installed Python3.5 & am using the library from there.

**Comment by FarizIbadov** [comment]
what to do if i am using python 3.7+?

**Comment by ashishnitinpatil** [comment]
I stopped using the library altogether I think. Currently using the APIs directly since my needs were limited to a couple APIs. You could always fork the repo, make the required changes for 3.7 & use that instead.
